In [7]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import requests
import math

In [8]:
percent_change_df = pd.read_csv("Output/scatter_data2.csv")
percent_change_df["CRIME_PERCENT_CHANGE"] = (percent_change_df["2020_TOTAL_CRIME"] - percent_change_df["2000_TOTAL_CRIME"])/(percent_change_df["2000_TOTAL_CRIME"])
percent_change_df["HOUSING_PERCENT_CHANGE"] = (percent_change_df["2020_AVERAGE_HOUSE_PRICE"] - percent_change_df["2000_AVERAGE_HOUSE_PRICE"])/(percent_change_df["2000_AVERAGE_HOUSE_PRICE"])
percent_change_df = percent_change_df[["NEIGHBORHOOD_NAME", "CRIME_PERCENT_CHANGE", "HOUSING_PERCENT_CHANGE"]]
percent_change_df

    NEIGHBORHOOD_NAME  CRIME_PERCENT_CHANGE  HOUSING_PERCENT_CHANGE
0            BEAUFONT             -0.012346                0.964726
1          BELLEMEADE             -0.427896                0.818124
2            BELLEVUE             -0.394068                1.490027
3       BELMONT WOODS             -0.428571                0.665115
4         BELT CENTER             -0.349650                0.893749
..                ...                   ...                     ...
115     WINDSOR FARMS             -0.295455                0.934349
116         WOODHAVEN              0.032787                1.050709
117  WOODLAND HEIGHTS             -0.416887                1.830848
118         WOODVILLE             -0.021127                0.044438
119       WORTHINGTON             -0.421687                0.917660

[120 rows x 3 columns]

In [9]:
# Save to csv
percent_change_df.to_csv("Output/percent_change.csv", encoding="utf-8", index=False)