In [43]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import requests
import math

In [44]:
# Pull in all crime data from 2000 - 2020
crime_2000 = pd.read_csv("Resources/Crime Information 2000.csv")
crime_2001 = pd.read_csv("Resources/Crime Information 2001.csv")
crime_2002 = pd.read_csv("Resources/Crime Information 2002.csv")
crime_2003 = pd.read_csv("Resources/Crime Information 2003.csv")
crime_2004 = pd.read_csv("Resources/Crime Information 2004.csv")
crime_2005 = pd.read_csv("Resources/Crime Information 2005.csv")
crime_2006 = pd.read_csv("Resources/Crime Information 2006.csv")
crime_2007 = pd.read_csv("Resources/Crime Information 2007.csv")
crime_2008 = pd.read_csv("Resources/Crime Information 2008.csv")
crime_2009 = pd.read_csv("Resources/Crime Information 2009.csv")
crime_2010 = pd.read_csv("Resources/Crime Information 2010.csv")
crime_2011 = pd.read_csv("Resources/Crime Information 2011.csv")
crime_2012 = pd.read_csv("Resources/Crime Information 2012.csv")
crime_2013 = pd.read_csv("Resources/Crime Information 2013.csv")
crime_2014 = pd.read_csv("Resources/Crime Information 2014.csv")
crime_2015 = pd.read_csv("Resources/Crime Information 2015.csv")
crime_2016 = pd.read_csv("Resources/Crime Information 2016.csv")
crime_2017 = pd.read_csv("Resources/Crime Information 2017.csv")
crime_2018 = pd.read_csv("Resources/Crime Information 2018.csv")
crime_2019 = pd.read_csv("Resources/Crime Information 2019.csv")
crime_2020 = pd.read_csv("Resources/Crime Information 2020.csv")

In [45]:
# Function to create Total Crime column and return DataFrame with just Neighborhood Name and Total Crime
def Total_Crime(year, df):
    df["TOTAL_CRIME"] = (df["HOMICIDE"] + df["SEX_OFFENSE"] + df["ROBBERY"] + 
                             df["ASSAULT"] + df["BURGLARY"] + df["VICE"] + 
                             df["THEFT"] + df["VEH_THEFT"] + df["OTHER"])
    df = df.rename(columns={"TOTAL_CRIME": f"{year}_TOTAL_CRIME"})
    df = df[["NEIGHBORHOOD_NAME", f"{year}_TOTAL_CRIME"]]
    return df

In [46]:
# Call Total_Crime function for each year
crime_2000 = Total_Crime("2000", crime_2000)
crime_2001 = Total_Crime("2001", crime_2001)
crime_2002 = Total_Crime("2002", crime_2002)
crime_2003 = Total_Crime("2003", crime_2003)
crime_2004 = Total_Crime("2004", crime_2004)
crime_2005 = Total_Crime("2005", crime_2005)
crime_2006 = Total_Crime("2006", crime_2006)
crime_2007 = Total_Crime("2007", crime_2007)
crime_2008 = Total_Crime("2008", crime_2008)
crime_2009 = Total_Crime("2009", crime_2009)
crime_2010 = Total_Crime("2010", crime_2010)
crime_2011 = Total_Crime("2011", crime_2011)
crime_2012 = Total_Crime("2012", crime_2012)
crime_2013 = Total_Crime("2013", crime_2013)
crime_2014 = Total_Crime("2014", crime_2014)
crime_2015 = Total_Crime("2015", crime_2015)
crime_2016 = Total_Crime("2016", crime_2016)
crime_2017 = Total_Crime("2017", crime_2017)
crime_2018 = Total_Crime("2018", crime_2018)
crime_2019 = Total_Crime("2019", crime_2019)
crime_2020 = Total_Crime("2020", crime_2020)

# Merge the crime data
merged_crime_df = pd.merge(crime_2000, crime_2001, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2002, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2003, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2004, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2005, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2006, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2007, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2008, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2009, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2010, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2011, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2012, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2013, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2014, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2015, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2016, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2017, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2018, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2019, on="NEIGHBORHOOD_NAME")
merged_crime_df = pd.merge(merged_crime_df, crime_2020, on="NEIGHBORHOOD_NAME")

# Add a new column that gives the mean of all the years
merged_crime_df["MEAN_TOTAL_CRIME"] = (
    (merged_crime_df["2000_TOTAL_CRIME"] + merged_crime_df["2001_TOTAL_CRIME"] + merged_crime_df["2002_TOTAL_CRIME"] + 
    merged_crime_df["2003_TOTAL_CRIME"] + merged_crime_df["2004_TOTAL_CRIME"] + merged_crime_df["2005_TOTAL_CRIME"] + 
    merged_crime_df["2006_TOTAL_CRIME"] + merged_crime_df["2007_TOTAL_CRIME"] + merged_crime_df["2008_TOTAL_CRIME"] + 
    merged_crime_df["2009_TOTAL_CRIME"] + merged_crime_df["2010_TOTAL_CRIME"] + merged_crime_df["2011_TOTAL_CRIME"] + 
    merged_crime_df["2012_TOTAL_CRIME"] + merged_crime_df["2013_TOTAL_CRIME"] + merged_crime_df["2014_TOTAL_CRIME"] + 
    merged_crime_df["2015_TOTAL_CRIME"] + merged_crime_df["2016_TOTAL_CRIME"] + merged_crime_df["2017_TOTAL_CRIME"] + 
    merged_crime_df["2018_TOTAL_CRIME"] + merged_crime_df["2019_TOTAL_CRIME"] + merged_crime_df["2020_TOTAL_CRIME"])/21
)

# Show new DataFrame
merged_crime_df

,NEIGHBORHOOD_NAME,2000_TOTAL_CRIME,2001_TOTAL_CRIME,2002_TOTAL_CRIME,2003_TOTAL_CRIME,2004_TOTAL_CRIME,2005_TOTAL_CRIME,2006_TOTAL_CRIME,2007_TOTAL_CRIME,2008_TOTAL_CRIME,...,2012_TOTAL_CRIME,2013_TOTAL_CRIME,2014_TOTAL_CRIME,2015_TOTAL_CRIME,2016_TOTAL_CRIME,2017_TOTAL_CRIME,2018_TOTAL_CRIME,2019_TOTAL_CRIME,2020_TOTAL_CRIME,MEAN_TOTAL_CRIME
0,ANCAROWS LANDING,31,31,51,26,33,32,35,41,56,...,26,23,36,26,27,20,27,33,32,33.047619
1,BEAUFONT,81,73,84,99,114,72,129,119,98,...,87,107,59,80,82,109,82,86,80,89.571429
2,BELLE AND MAYO ISLANDS,8,4,3,16,16,27,27,57,115,...,152,92,59,86,62,78,52,69,24,62.428571
3,BELLEMEADE,846,770,700,681,659,650,793,760,765,...,597,658,562,613,620,676,685,644,484,668.333333
4,BELLEVUE,236,160,155,173,124,122,135,100,122,...,174,186,148,150,138,115,110,139,143,140.761905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,WINDSOR FARMS,44,42,90,26,35,33,30,47,43,...,34,73,36,16,32,39,38,27,31,37.238095
140,WOODHAVEN,122,165,140,127,161,187,195,243,169,...,187,158,144,144,135,111,103,131,126,157.047619
141,WOODLAND HEIGHTS,379,552,541,376,342,332,338,282,233,...,224,231,230,326,329,337,289,284,221,318.095238
142,WOODVILLE,142,131,166,148,144,132,148,145,142,...,95,108,114,100,119,160,145,160,139,138.666667
143,WORTHINGTON,83,75,68,62,88,67,92,93,102,...,94,75,101,74,84,55,78,82,48,81.190476

In [47]:
# Add Zillow's Average House Price data to the DataFrame
# Pull in Zillow Data
zillow_df = pd.read_csv("Output/zillow_by_year.csv")

# Convert Region Name to Upper Case
zillow_df["Region Name"] = zillow_df["Region Name"].str.upper()

# Change Region Name to NEIGHBORHOOD_NAME
zillow_df = zillow_df.rename(columns={"Region Name": "NEIGHBORHOOD_NAME"})

# Rename years                       
years = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 
         2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

for year in years:
    zillow_df = zillow_df.rename(columns={f"{year}": f"{year}_AVERAGE_HOUSE_PRICE"})
                            
# Remove columns that are not needed
zillow_df = zillow_df.drop(columns=["Region ID", "Size Rank", "Zip Code", "Second Zip Code", "Third Zip Code", 
                                    "1996", "1997", "1998", "1999", "01/2021 - 07/2021"])

# Add a new column that gives the mean of all the years
zillow_df["MEAN_TOTAL_HOUSE_PRICE"] = (
    (zillow_df["2000_AVERAGE_HOUSE_PRICE"] + zillow_df["2001_AVERAGE_HOUSE_PRICE"] + zillow_df["2002_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2003_AVERAGE_HOUSE_PRICE"] + zillow_df["2004_AVERAGE_HOUSE_PRICE"] + zillow_df["2005_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2006_AVERAGE_HOUSE_PRICE"] + zillow_df["2007_AVERAGE_HOUSE_PRICE"] + zillow_df["2008_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2009_AVERAGE_HOUSE_PRICE"] + zillow_df["2010_AVERAGE_HOUSE_PRICE"] + zillow_df["2011_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2012_AVERAGE_HOUSE_PRICE"] + zillow_df["2013_AVERAGE_HOUSE_PRICE"] + zillow_df["2014_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2015_AVERAGE_HOUSE_PRICE"] + zillow_df["2016_AVERAGE_HOUSE_PRICE"] + zillow_df["2017_AVERAGE_HOUSE_PRICE"] + 
    zillow_df["2018_AVERAGE_HOUSE_PRICE"] + zillow_df["2019_AVERAGE_HOUSE_PRICE"] + zillow_df["2020_AVERAGE_HOUSE_PRICE"])/21
)

# Merge crime data and zillow data and clean up order of columns
merged_crime_df = pd.merge(merged_crime_df, zillow_df, on="NEIGHBORHOOD_NAME")


#merged_crime_df = merged_crime_df[["NEIGHBORHOOD_NAME", "2000_TOTAL_CRIME", "2000_AVERAGE_HOUSE_PRICE",
#                                   "2010_TOTAL_CRIME", "2010_AVERAGE_HOUSE_PRICE",
#                                   "2020_TOTAL_CRIME", "2020_AVERAGE_HOUSE_PRICE"]]

# Show new DataFrame
merged_crime_df

,NEIGHBORHOOD_NAME,2000_TOTAL_CRIME,2001_TOTAL_CRIME,2002_TOTAL_CRIME,2003_TOTAL_CRIME,2004_TOTAL_CRIME,2005_TOTAL_CRIME,2006_TOTAL_CRIME,2007_TOTAL_CRIME,2008_TOTAL_CRIME,...,2012_AVERAGE_HOUSE_PRICE,2013_AVERAGE_HOUSE_PRICE,2014_AVERAGE_HOUSE_PRICE,2015_AVERAGE_HOUSE_PRICE,2016_AVERAGE_HOUSE_PRICE,2017_AVERAGE_HOUSE_PRICE,2018_AVERAGE_HOUSE_PRICE,2019_AVERAGE_HOUSE_PRICE,2020_AVERAGE_HOUSE_PRICE,MEAN_TOTAL_HOUSE_PRICE
0,BEAUFONT,81,73,84,99,114,72,129,119,98,...,116402,113647,110738,115794,133430,136345,149896,161228,179741,128859.000000
1,BELLEMEADE,846,770,700,681,659,650,793,760,765,...,60356,61080,65558,59610,58628,65129,79389,93220,110851,72656.238095
2,BELLEVUE,236,160,155,173,124,122,135,100,122,...,237716,251652,257725,266497,282936,300601,320885,335723,356034,247759.095238
3,BELMONT WOODS,28,27,24,12,31,27,53,41,27,...,124702,122213,130302,136354,142739,150620,168113,177865,199649,145213.476190
4,BELT CENTER,715,756,550,569,446,417,452,420,468,...,85432,76923,81764,82464,77722,88260,97496,113206,142836,93103.523810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,WINDSOR FARMS,44,42,90,26,35,33,30,47,43,...,823875,881713,883240,888073,925445,953437,994608,1050626,1098946,855789.428571
116,WOODHAVEN,122,165,140,127,161,187,195,243,169,...,86105,98527,90518,99146,107985,114328,125116,129594,155251,106224.000000
117,WOODLAND HEIGHTS,379,552,541,376,342,332,338,282,233,...,206450,217644,217463,236378,249152,269610,288871,307341,331597,218927.380952
118,WOODVILLE,142,131,166,148,144,132,148,145,142,...,100255,85785,76264,82503,78151,83901,97534,125285,144709,115771.095238
119,WORTHINGTON,83,75,68,62,88,67,92,93,102,...,93232,96931,106930,114749,123371,129336,141223,150958,163726,118076.238095

In [48]:
# Save new output to csv
merged_crime_df.to_csv("Output/scatter_data2.csv", encoding="utf-8", index=False)